Updated .gitignore file, includes Node, MySQL, Docker, GraphQL, and V…
BroncoDirectMe/Backend pull request #14
Opened 2022-09-16 04:59 UTC by PattyCakesxD

I sort of just copy and pasted those gitignores, other than that I have no clue what I'm doing

2022-09-16 05:06 UTC, misslame commented
Did you add every possible scenario file you can think of to being ignored? Like I saw c++ and .NET generated files there.

2022-09-16 05:07 UTC, misslame commented
Also did you check if it does indeed ignore the files we care about. Lol I would check myself but im on my phone and it scrolls for days.

2022-09-16 05:09 UTC, PattyCakesxD commented
Didn't know what qualifies as valid files to ignore unless it requires extensive research (I know nothing about MySQL, Node, and Docker) so I just copy and pasted the gitignores of the examples in the task. Is this really as easy as it's marked?

2022-09-22 01:42 UTC, PattyCakesxD commented
Updated .gitignore again

A lot of files were irrelevant to THIS sprint, but I kept the ones that are generally important for each respective category (albeit I deemed some files as important even though not 100% sure on their purpose). If the .gitignore only needs to pertain exactly for what's required in this sprint, the custom .gitignore would be about 5 lines long. Let me know if I did anything wrong with the update please!

2022-09-22 05:15 UTC, GuyWhoCode requested changes

2022-09-22 05:15 UTC, GuyWhoCode commented on .gitignore
> +# dotenv environment variable files
This is an optional trim if the desired outcome is to reduce the amount of files in `.gitignore`. As far as I'm aware, `.env` should be the only file used for environment variables.  Local / production environments usually have their own instance of a `.env` file.

2022-09-22 05:15 UTC, GuyWhoCode commented on .gitignore
> +# ------- MySQL ignore -------
I haven't encountered any of these files when writing MySQL for my issue. These files under the `MySQL ignore` can be removed.

2022-09-22 05:21 UTC, misslame approved these changes

2022-09-22 05:32 UTC, GuyWhoCode approved these changes

2022-09-28 02:39 UTC, merged